### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by eddelbuettel** [ess-intro/presentation-ess-from-spacemacs#6]
Just wanted to say well done!  I really enjoyed those four minutes, and it is really well paced.

It is also weird just how different these turn out to be. I learned a lot from @frederic-santos 's video and he did a great job calmly walking through actual setups for customization.  So with that if there was one thing you could have added ... it might have been video of _using_ spaceemacs which is left in the notes.

(Also, do we need a better place for feedback somewhere?)

**Comment by aezarebski** [comment]
Thanks, it's been a rewarding process! 

I completely agree a demo would have been good, but 4 minutes of my voice was already more than I could stand, and more to the point, since there isn't a particular feature i wanted to demonstrate, I couldn't think of anything intrinsic to spacemacs that I wanted to demonstrate other than the keybindings. 

regarding feedback/questions, i think the best place for them is the individual presentations' issue tracker (it is pretty much made for this purpose anyway). The location should probably be made explicit in the video/description i guess, I can't remember if I did so...

Actually, now I think of it, I'll put a comment on the website to that effect, if you disagree, no worries, happy to remove it again afterwards.

**Comment by eddelbuettel** [comment]
Yes per-presentation feedback would map well to per-presentation repos.  Maybe we can add a line to top-level page and/or the wiki?

**Comment by aezarebski** [comment]
Done and done
